### ISSUE TITLE
get up and running!

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/gryph#1]
get up and running a chat app lol

**Comment by jaredgrady** [comment]
Alright lets do this

**Comment by Irraquated** [comment]
what is this
e: nvm lol

**Comment by CreaturePhil** [comment]
@Irraquated irraquated's total ontime is 0 hours 55 minutes 17 seconds.
![noface](http://i.imgur.com/H744eRE.png)

**Comment by Irraquated** [comment]
staying concentrated on school for a while
I should be more active on origin in the coming week or so

**Comment by CreaturePhil** [comment]
unfortunately due to bad internet and other various events, i will be extending the deadline for this by 2 weeks lol
