### ISSUE TITLE
Features To-Do List 

### ISSUE THREAD

**Issue by jaredgrady** [FakeSloth/gryph#13]
Features to add: 
- [x] Usergroups/Ranks 
- [x] Moderation and chat commands 
- [x] Queue/Playlists
- [ ] Style

**Comment by jaredgrady** [comment]
Authority Groups: 

Admin = (symbol to be decided)
Mod = (@)
Operator = ($)
Voice = (^ or *)

**Comment by CreaturePhil** [comment]
@TheFenderStory They are corny. **corny:** Trying to be cool, but ultimately very uncool indeed, and often even extremely embarrassing

**Comment by jaredgrady** [comment]
Well lets come up with some that are not total clones of another open source project xaa

**Comment by jaredgrady** [comment]
I've updated the comment with the new ideas.

**Comment by Irraquated** [comment]
Does operator really need to be a thing?
It was kinda only implemented because back in the day naten didn't trust people™ to be in the staff room

**Comment by jaredgrady** [comment]
We based it off traditional IRC usergroups.

**Comment by CreaturePhil** [comment]
@TheFenderStory what are styles? we are almost done with the checklist.

**Comment by jaredgrady** [comment]
Logo mainly, also the about page needs to be done up nicely.

**Comment by CreaturePhil** [comment]
@TheFenderStory Is the style ever going to be finished?

**Comment by CreaturePhil** [comment]
fender: sure
