### ISSUE TITLE
Organizing Commands

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/gryph#14]
How should we organize commands?

Different files can be:
Moderation, Info (help), video, etc.?

**Comment by jaredgrady** [comment]
Yeah that organization makes sense. we should probably just group them all in a commands folder, and just assemble the files as such. As we add more chat-commands we can decide if a better organization is needed.

**Comment by DarkNightSkies** [comment]
imo you should organize the commands the way phil said becasue of easy access and the commands file won't be spammed with commands.

**Comment by jaredgrady** [comment]
:+1:

**Comment by jaredgrady** [comment]
@CreaturePhil do we want to close this issue and open a new one with an organized list of all the commands we need to make?

**Comment by CreaturePhil** [comment]
@TheFenderStory sure
