### ISSUE TITLE
Let's Start Chatting

### ISSUE THREAD

**Issue by jaredgrady** [FakeSloth/gryph#2]
To-do for v0.1.0:
1. Add login functionality
2. Add support for usernames in chat
3. Improve chat side overflow
4. Style chat

**Comment by CreaturePhil** [comment]
- [x] improve width of chat (side overflow)
- [x] username support
- [x] userlist
- [x] save chat history on initial load (100 lines or so)

**Comment by CreaturePhil** [comment]
Todos for upcoming version:
- [x] escapeHTML
- [x] add emote support
- [x] better error messages
- [x] more checks for invalid usernames (a-z, length, etc.)
- [x] markdown support (bold, links, etc.)
- [x] sort userlist alphabetically
- [ ] commands?

irra reported that the charbar is too low, so probably move it up a bit

**Comment by jaredgrady** [comment]
Lets save chat commands for a later milestone

**Comment by CreaturePhil** [comment]
yeah, also user ranks and better chat moderation like throttling someone trying to spam

**Comment by jaredgrady** [comment]
Closing issue, commands will be dealt with in a later milestone.
