### ISSUE TITLE
Userlist gets out of sync with idle users

### ISSUE THREAD

**Issue by panpawn** [FakeSloth/gryph#6]
If someone idles too long, they don't disconnect, but their name disappears from the userlist.  (They can still talk in the chat, though.)

**Comment by CreaturePhil** [comment]
@panpawn what do you think is the solution to this?

**Comment by jaredgrady** [comment]
We probably need an idle timer and to disconnect the user when it expires.

**Comment by CreaturePhil** [comment]
@TheFenderStory pruneGhostUsers? https://github.com/Zarel/Pokemon-Showdown/blob/b6656606080506d50e42493e0a81bb7cad1da161/users.js#L1605

**Comment by jaredgrady** [comment]
Yeah thats probably what we are gonna need to do

**Comment by panpawn** [comment]
Before trying to add something like that, we should try to figure out why the userlist seems to desync after a certain period of time.

**Comment by jaredgrady** [comment]
Is this issue still relevant with our current build?

**Comment by CreaturePhil** [comment]
@TheFenderStory not sure. We'll have to wait and see if it happens on a larger userbase
